### ISSUE TITLE
Make homepage error messages more appealing

### ISSUE THREAD

**Issue by eitan12345om** [jukeboxroundtable/JukeboxRoundtable#20]
Right now if you enter the incorrect password or a non-existent party when joining, or enter an existing party name when creating, the error messages don't look very nice. Can you fix this?

**Comment by zacharynoel** [comment]
For sure. Saw how it currently looks. Do you think a pop-up alert would look better, or still an error message on the page itself, just in a more appropriate spot?

**Comment by eitan12345om** [comment]
I think that the error message should stay on the page in a more appropriate spot. Maybe make it red too?

**Comment by zacharynoel** [comment]
Done for both, now is right above the input form and red.
