### ISSUE TITLE
Remove the jukebox page altogether?

### ISSUE THREAD

**Issue by eitan12345om** [jukeboxroundtable/JukeboxRoundtable#25]

**Comment by zacharynoel** [comment]
What do you mean? Replacing it with something?

**Comment by eitan12345om** [comment]
Check out my latest pull request.
Essentially, this would get rid of the jukeboxrt.herokuapp.com/<party_name>. If anyone joined a party, the URL on their address bar would remain jukeboxrt.herokuapp.com

**Comment by zacharynoel** [comment]
Oh I see what you mean. Given the shift we've made with how joining the rooms work, I do think that would then be better. No need for it to append the party name when we don't want people joining from a specific room URL anymore. Approved pull request.
