### ISSUE TITLE
Jukebox Round Table needs a name change

### ISSUE THREAD

**Issue by eitan12345om** [jukeboxroundtable/JukeboxRoundtable#38]
The name is really long and it doesn't really fit the demographic.

**Comment by zacharynoel** [comment]
I agree, I wouldn't mind just "Jukebox" or "Jukebox.io" instead, something still with the Jukebox theme but without the Roundtable part.

**Comment by dziermanfelix** [comment]
The whole premise of this project is based on my uncle coming up with the idea of "Jukebox Roundtable", which is a way of offering each person in a group the opportunity to choose a song to play. It is thought of as literally putting a jukebox on a roundtable so each person can pick a song when it is his or her turn. To change the name is to change the meaning, leading to the point of the project being lost. The url for the website has already been shortened to "jukeboxrt" to ease access for users. Jukebox Roundtable is affecting no one by being displayed on the homepage.
