### ISSUE TITLE
Heroku Account Is Not Provisioned

### ISSUE THREAD

**Issue by eitan12345om** [jukeboxroundtable/JukeboxRoundtable#42]
I need to add an add-on "Heroku Scheduler" so that we can run asynchronous tasks (cron jobs). However, when trying to do so, I get the following error:

Item could not be created:
The owner of jukeboxrt, dziermanfelix@gmail.com, must be verified before you can install this add-on plan (please have them enter a credit card)
For more information, see https://devcenter.heroku.com/categories/billing

@dziermanfelix Can you please verify your account?

**Comment by dziermanfelix** [comment]
@eitan12345om I added the credit card.
