### ISSUE TITLE
Continuous Integration Setup

### ISSUE THREAD

**Issue by dziermanfelix** [jukeboxroundtable/JukeboxRoundtable#6]
- [x] Write some tests.
- [x] Make sure TravisCI runs tests.
- [x] Make sure it stops deployment if broken.
- [ ] Add SonarQube

**Comment by eitan12345om** [comment]
@dziermanfelix I need ownership permissions to connect Travis with this repo

**Comment by dziermanfelix** [comment]
@eitan12345om Ownership permissions coming your way
